### ISSUE TITLE
Broken Regions

### ISSUE THREAD

**Issue by Ben1138** [WHSnyder/SWBF2-.lvl-Extraction-Tools-for-Unity3D#3]
Importing of regions seems to be broken on occasions. Sometimes, the imported regions don't match up at all.
Looks like it's because of broken scale values? One example the Z scale of cp3concapture on kashyyyk is 0.1 instead of 10.

![grafik](https://user-images.githubusercontent.com/8263806/150680224-5197634f-b7e2-4bdf-b9a8-3f58beedc8fc.png)
![grafik](https://user-images.githubusercontent.com/8263806/150680235-d098222a-de0b-4f5d-86e8-3c31d6a33984.png)
![grafik](https://user-images.githubusercontent.com/8263806/150680248-78df4b86-efa8-4e91-94e4-98b7c5edb35f.png)

**Comment by WHSnyder** [comment]
Should be fixed now...

**Comment by WHSnyder** [comment]
c73a076b2e778f5ca536dccac808beb51704f5b5 should fix the most egregious offenses, but cylinder scaling is still gonna be slightly off.  When scaling cylinders in ZE, ```Y``` does the height ofc, but ```X``` and ```Z``` both do the radius.  The logical conclusion would be that ```X``` and ```Z``` can be scaled differently to produce ellipse regions and this kind of happens at smaller sizes, but it is not the case overall.  There are effectively two parameters: ```radius``` and ```height```.  It is not clear how ```radius``` is calculated from the combination of ```X``` and ```Z``` scales.  It isn't exactly additive, i.e. if one sets ```X``` to 8 and ```Z``` to 0 (or ```Z``` to 8 and ```X``` to 0) the result is smaller than if ```X``` and ```Z``` are both 4.  Will keep the issue open until the exact behavior is reversed.

**Comment by WHSnyder** [comment]
Duh, radial scale is just hypotenuse(x,z)
