### ISSUE TITLE
Cant build after using lvl Importer

### ISSUE THREAD

**Issue by WilleLX1** [WHSnyder/SWBF2-.lvl-Extraction-Tools-for-Unity3D#5]
Assets\LVLImport\Loaders\WorldLoader.cs(585,17): error CS1061: 'TerrainData' does not contain a definition for 'SetTerrainLayersRegisterUndo' and no accessible extension method 'SetTerrainLayersRegisterUndo' accepting a first argument of type 'TerrainData' could be found (are you missing a using directive or an assembly reference?)

Assets\LVLImport\Loaders\WorldLoader.cs(746,27): error CS1061: 'Light' does not contain a definition for 'lightmapBakeType' and no accessible extension method 'lightmapBakeType' accepting a first argument of type 'Light' could be found (are you missing a using directive or an assembly reference?)

Assets\LVLImport\Loaders\Loader.cs(55,18): error CS0103: The name 'AssetDatabase' does not exist in the current context

Assets\LVLImport\Loaders\Loader.cs(57,17): error CS0103: The name 'AssetDatabase' does not exist in the current context

Assets\LVLImport\Loaders\Loader.cs(57,47): error CS0103: The name 'AssetDatabase' does not exist in the current context

Assets\LVLImport\Loaders\TextureLoader.cs(59,17): error CS0103: The name 'AssetDatabase' does not exist in the current context

Assets\LVLImport\Loaders\TextureLoader.cs(59,52): error CS0103: The name 'ImportAssetOptions' does not exist in the current context

Assets\LVLImport\Loaders\TextureLoader.cs(60,42): error CS0103: The name 'AssetDatabase' does not exist in the current context

Assets\LVLImport\Loaders\AnimationLoader.cs(162,22): error CS0103: The name 'AssetDatabase' does not exist in the current context

Assets\LVLImport\Loaders\AnimationLoader.cs(164,21): error CS0103: The name 'AssetDatabase' does not exist in the current context

Assets\LVLImport\Loaders\AnimationLoader.cs(164,51): error CS0103: The name 'AssetDatabase' does not exist in the current context

Assets\LVLImport\Loaders\AnimationLoader.cs(167,17): error CS0103: The name 'AssetDatabase' does not exist in the current context

Assets\LVLImport\Loaders\MaterialLoader.cs(191,25): error CS0103: The name 'AssetDatabase' does not exist in the current context

Assets\LVLImport\Loaders\MaterialLoader.cs(229,13): error CS0103: The name 'AssetDatabase' does not exist in the current context

Assets\LVLImport\Loaders\MaterialLoader.cs(229,35): error CS0103: The name 'ImportAssetOptions' does not exist in the current context

Assets\LVLImport\Loaders\ModelLoader.cs(114,13): error CS0103: The name 'AssetDatabase' does not exist in the current context

Assets\LVLImport\Loaders\ClassLoader.cs(228,29): error CS0103: The name 'PrefabUtility' does not exist in the current context

Assets\LVLImport\Loaders\ClassLoader.cs(399,41): error CS0103: The name 'PrefabUtility' does not exist in the current context

Assets\LVLImport\Loaders\ClassLoader.cs(399,132): error CS0103: The name 'InteractionMode' does not exist in the current context

Assets\LVLImport\Loaders\WorldLoader.cs(333,13): error CS0103: The name 'AssetDatabase' does not exist in the current context

Assets\LVLImport\Loaders\WorldLoader.cs(356,13): error CS0103: The name 'AssetDatabase' does not exist in the current context

Assets\LVLImport\Loaders\WorldLoader.cs(411,17): error CS0103: The name 'AssetDatabase' does not exist in the current context

Assets\LVLImport\Loaders\WorldLoader.cs(411,59): error CS0103: The name 'ImportAssetOptions' does not exist in the current context

Assets\LVLImport\Loaders\WorldLoader.cs(412,39): error CS0103: The name 'AssetDatabase' does not exist in the current context

Assets\LVLImport\Loaders\WorldLoader.cs(426,13): error CS0103: The name 'PrefabUtility' does not exist in the current context

Assets\LVLImport\Loaders\WorldLoader.cs(426,115): error CS0103: The name 'InteractionMode' does not exist in the current context

Assets\LVLImport\Loaders\ClassLoader.cs(421,17): error CS0103: The name 'PrefabUtility' does not exist in the current context

Assets\LVLImport\Loaders\ClassLoader.cs(421,82): error CS0103: The name 'PrefabUnpackMode' does not exist in the current context

Assets\LVLImport\Loaders\ClassLoader.cs(421,111): error CS0103: The name 'InteractionMode' does not exist in the current context

Assets\LVLImport\Loaders\WorldLoader.cs(535,13): error CS0103: The name 'AssetDatabase' does not exist in the current context

Assets\LVLImport\Loaders\WorldLoader.cs(615,13): error CS0103: The name 'PrefabUtility' does not exist in the current context

Assets\LVLImport\Loaders\WorldLoader.cs(615,115): error CS0103: The name 'InteractionMode' does not exist in the current context

Assets\LVLImport\Loaders\ModelLoader.cs(550,25): error CS0103: The name 'AssetDatabase' does not exist in the current context

Assets\LVLImport\Loaders\WorldLoader.cs(801,21): error CS0103: The name 'PrefabUtility' does not exist in the current context

Assets\LVLImport\Loaders\WorldLoader.cs(801,136): error CS0103: The name 'InteractionMode' does not exist in the current context

Assets\LVLImport\Loaders\WorldLoader.cs(835,17): error CS0103: The name 'PrefabUtility' does not exist in the current context

Assets\LVLImport\Loaders\WorldLoader.cs(835,131): error CS0103: The name 'InteractionMode' does not exist in the current context

Error building Player because scripts had compiler errors

Build completed with a result of 'Failed' in 5 seconds (4713 ms)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

UnityEditor.BuildPlayerWindow+BuildMethodException: 38 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002ca] in <208f92fc783546f9abbe643bfc23920c>:0 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <208f92fc783546f9abbe643bfc23920c>:0 
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by WHSnyder** [comment]
https://github.com/LibSWBF2/SWBF2-.lvl-Extraction-Tools-for-Unity3D#usage bullet point 4.
